# Constants for MySingingMonstersAutoBot

# Images

PLAY = "Images\\play.png"
USE = "Images\\use.png"
TIMEOUT = "Images\\timeout.png"
OK = "Images\\ok.png"
CLOSE = "Images\\close.png"
COLLECT = "Images\\collect.png"
COLLECTALL = "Images\\collectAll.png"
COLLECTALLNO = "Images\\collectAllNo.png"
CONFIRM = "Images\\confirm.png"
CONTINUE = "Images\\continue.png"
FOOD = "Images\\food.png"
GEM = "Images\\gem.png"
GO = "Images\\go.png"
GOLD = "Images\\gold.png"
MAP = "Images\\map.png"
MIRROR = "Images\\mirror.png"
MSM = "Images\\msm.png"
NEXT = "Images\\next.png"
RETRY = "Images\\retry.png"
UNMIRROR = "Images\\unMirror.png"
NOTI = "Images\\noti.png"
NOTI2 = "Images\\noti2.png"
MAILBOX = "Images\\mailbox.png"

PLANT = "Images\\plant_select.png"
COLD = "Images\\cold_select.png"
AIR = "Images\\air_select.png"
WATER = "Images\\water_select.png"
EARTH = "Images\\earth_select.png"
SHUGABUSH = "Images\\shugabush_select.png"
ETHEREAL = "Images\\ethereal_select.png"
ETHEREALWORKSHOP = "Images\\etherealWorkshop_select.png"
FIREHAVEN = "Images\\fireHaven_select.png"
FIREOASIS = "Images\\fireOasis_select.png"
LIGHT = "Images\\light_select.png"
PSYCHIC = "Images\\psychic_select.png"
FAERIE = "Images\\faerie_select.png"
BONE = "Images\\bone_select.png"
MAGICALSANCTUM = "Images\\magicalSanctum_select.png"
SEASONAL = "Images\\seasonalShanty_select.png"
WUBLIN = "Images\\wublin_select.png"


MIRROR_PLANT = "Images\\mirror_plant_select.png"
MIRROR_COLD = "Images\\mirror_cold_select.png"
MIRROR_AIR = "Images\\mirror_air_select.png"
MIRROR_WATER = "Images\\mirror_water_select.png"
MIRROR_EARTH = "Images\\mirror_earth_select.png"

PLANT_ISLAND = "Images\\plant.png"
COLD_ISLAND = "Images\\cold.png"
AIR_ISLAND = "Images\\air.png"
WATER_ISLAND = "Images\\water.png"
EARTH_ISLAND = "Images\\earth.png"
SHUGABUSH_ISLAND = "Images\\shugabush.png"
ETHEREAL_ISLAND = "Images\\ethereal.png"
ETHEREALWORKSHOP_ISLAND = "Images\\etherealWorkshop.png"
FIREHAVEN_ISLAND = "Images\\fireHaven.png"
FIREOASIS_ISLAND = "Images\\fireOasis.png"
LIGHT_ISLAND = "Images\\light.png"
PSYCHIC_ISLAND = "Images\\psychic.png"
FAERIE_ISLAND = "Images\\faerie.png"
BONE_ISLAND = "Images\\bone.png"
MAGICALSANCTUM_ISLAND = "Images\\magicalSanctum.png"
SEASONAL_ISLAND = "Images\\seasonalShanty.png"
WUBLIN_ISLAND = "Images\\wublin.png"

MIRROR_PLANT_ISLAND = "Images\\mirror_plant.png"
MIRROR_COLD_ISLAND = "Images\\mirror_cold.png"
MIRROR_AIR_ISLAND = "Images\\mirror_air.png"
MIRROR_WATER_ISLAND = "Images\\mirror_water.png"
MIRROR_EARTH_ISLAND = "Images\\mirror_earth.png"

# proud of this lil piece of code so ill keep it here
# import os
# for image in os.listdir("Images"):
#     print(f"{(image[0:-4]).upper()} = \"Images\\\\{image}\"")